// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpK2j3OVbfd0hY8Fyc3kI-udPSs7AzZcg',
    appId: '1:91606143072:web:17d4d655a85739a729f305',
    messagingSenderId: '91606143072',
    projectId: 'light-tinted-miaged',
    authDomain: 'light-tinted-miaged.firebaseapp.com',
    storageBucket: 'light-tinted-miaged.appspot.com',
    measurementId: 'G-QFR0F3L166',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASc3IJii0I7r6lLL12uMuJWfrwoEEq7xw',
    appId: '1:91606143072:android:c70e9582c56b6ee329f305',
    messagingSenderId: '91606143072',
    projectId: 'light-tinted-miaged',
    storageBucket: 'light-tinted-miaged.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnnRxlZNJlVS1M3iXISu-X8MEFRkmgQA',
    appId: '1:91606143072:ios:1b5278f8f902dc9429f305',
    messagingSenderId: '91606143072',
    projectId: 'light-tinted-miaged',
    storageBucket: 'light-tinted-miaged.appspot.com',
    iosClientId: '91606143072-vcc5fop2hdouh4rn33ovuok739fd821f.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightVinted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnnRxlZNJlVS1M3iXISu-X8MEFRkmgQA',
    appId: '1:91606143072:ios:1b5278f8f902dc9429f305',
    messagingSenderId: '91606143072',
    projectId: 'light-tinted-miaged',
    storageBucket: 'light-tinted-miaged.appspot.com',
    iosClientId: '91606143072-vcc5fop2hdouh4rn33ovuok739fd821f.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightVinted',
  );
}
